version: "3"
services:
  react-app: 
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=imronxz
      # CHOKIDAR_USEPOLLING=true -> for windows root Docker
    # env_file:
    #   - ./.env

