version: "3"
services:
  react-app: 
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=imronxz-prod
    ports:
      - "8080:80"
    
    # env_file:
    #   - ./.env

